services:   # render.yaml (Docker-only version)
  - type: web
    name: purchase-prediction-api
    dockerfile: Dockerfile  # Render will use ONLY this
    envVars:
      - key: R_ENABLE_JIT
        value: "3"
      - key: PORT
        value: "8000"  # Must match Dockerfile EXPOSE
    healthCheckPath: /health
    autoDeploy: true