services:
  - type: web
    name: purchase-prediction-api
    runtime: r  # Explicitly declare R runtime
    env: r
    buildCommand: |
      Rscript -e "install.packages(c('plumber', 'dplyr', 'caret'), repos='https://cloud.r-project.org', Ncpus=2)"
      Rscript -e "if (!file.exists('api/purchase_model.rds')) { stop('Model file missing!') }"
      Rscript -e "print(R.version)"
    startCommand: Rscript -e "plumber::plumb('api/plumber.R')$run(port=$PORT, host='0.0.0.0')"
    envVars:
      - key: R_ENABLE_JIT
        value: 3
      - key: MODEL_PATH
        value: /opt/render/project/src/api/purchase_model.rds   
    healthCheckPath: /health
    autoDeploy: true
    plan: free  # For paid tier: change to "standard" 